### ISSUE TITLE
Chinese cannot be displayed properly in `Arctic Fuse 2`

### ISSUE THREAD

**Issue by iamxiaojianzheng** [jurialmunkey/resource.font.robotocjksc#1] opened 2024-11-26 08:59 UTC
![image](https://github.com/user-attachments/assets/39f71098-a2fc-4785-94bb-8c24797378f6)

![image](https://github.com/user-attachments/assets/b4e21f6b-4de3-4f65-866b-8cdcbdf2e09e)

Appears normal in `Arctic Horizon 2`
![image](https://github.com/user-attachments/assets/ee5e142c-6e74-44cc-9b35-ff24f2840326)

**Comment by iamxiaojianzheng** [comment] 2024-11-26 09:01
Font choose `CJK - Chinese/Japanese/Korean`
Language choose `Chinese(Simple)`

**Comment by jurialmunkey** [comment] 2024-11-26 09:14
Duplicate of https://github.com/jurialmunkey/skin.arctic.fuse.2/issues/339

**Closed as not planned by jurialmunkey** 2024-11-26 09:14 UTC
